# Generated by Django 5.0.6 on 2024-07-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_entrada',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_saida',
            field=models.TimeField(default='00:00'),
        ),
    ]
